### ISSUE TITLE
Bug: Invalid default values disable program

### ISSUE THREAD

**Issue by rgzn** [EarToEarOak/RF-Monitor#4]
When running the gui through 
`python rfmonitor.py`
You can set the frequency to something invalid, like 0. 
If you do this, and close the program, if you reopen it it fails with the following error message:

> Traceback (most recent call last):
>  File "rfmonitor.py", line 83, in <module>
>    frame = FrameMain()
> File "/home/j/src/RF-Monitor/rfmonitor/gui.py", line 133, in __init__
>  self._toolbar.set_freq(self._settings.get_freq())
> File "/home/j/src/RF-Monitor/rfmonitor/toolbar.py", line 179, in set_freq
>    self._numFreq.SetValue(freq)
>  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/masked/numctrl.py", line 1281, in SetValue
>    BaseMaskedTextCtrl.SetValue( self, self._toGUI(value) )
>  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/masked/numctrl.py", line 1604, in _toGUI
>    'value %d is below minimum value of control'% value )
> ValueError: value 0 is below minimum value of control

**Comment by EarToEarOak** [comment]
I didn't manage to set the frequency input to zero, but I have added range checks to stop the crash you are seeing in 506b12bdc06d8c1a76d2dc6f541cdffbef43ed06.
